name: Local CI - Serverless URL Shortener
on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest boto3

       - name: Debug workspace
        run: |
          pwd
          python -V
          ls -la
          ls -la lambda_fn || true
          ls -la tests || true

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -q
