name: Deploy URL Shortener
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init/plan/apply
        run: |
          terraform -chdir=infra init -backend=false
          terraform -chdir=infra plan -out=tfplan
          terraform -chdir=infra apply -auto-approve tfplan

      - name: Output API endpoint
        run: terraform -chdir=infra output -raw api_endpoint || true
